/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lasagna.hangman.start;
//package lasagna.hangman.start.folder;

/**
 *
 * @author nic
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whatitdo = new javax.swing.JPanel();
        playbtn = new javax.swing.JButton();
        highscoresbtn = new javax.swing.JButton();
        creditsbtn = new javax.swing.JButton();
        dancingman = new javax.swing.JLabel();
        lasagna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        whatitdo.setBackground(new java.awt.Color(153, 153, 255));
        whatitdo.setForeground(new java.awt.Color(153, 153, 255));
        whatitdo.setToolTipText("");
        whatitdo.setPreferredSize(new java.awt.Dimension(600, 400));
        whatitdo.setLayout(null);

        playbtn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        playbtn.setText("PLAY");
        playbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbtnActionPerformed(evt);
            }
        });
        whatitdo.add(playbtn);
        playbtn.setBounds(30, 320, 160, 40);

        highscoresbtn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        highscoresbtn.setText("HIGHSCORES");
        highscoresbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoresbtnActionPerformed(evt);
            }
        });
        whatitdo.add(highscoresbtn);
        highscoresbtn.setBounds(230, 320, 160, 40);

        creditsbtn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        creditsbtn.setText("CREDITS");
        creditsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsbtnActionPerformed(evt);
            }
        });
        whatitdo.add(creditsbtn);
        creditsbtn.setBounds(420, 320, 160, 40);

        dancingman.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\5a65dcc4e4a067fc85e1c85a3d8809d0.gif")); // NOI18N
        dancingman.setLabelFor(dancingman);
        whatitdo.add(dancingman);
        dancingman.setBounds(280, -40, 310, 260);

        lasagna.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\58f5578a4be18ec292b7a4374bebbe3f-lasagna-dish-illustration.png")); // NOI18N
        whatitdo.add(lasagna);
        lasagna.setBounds(0, 0, 260, 230);

        getContentPane().add(whatitdo, java.awt.BorderLayout.CENTER);
        whatitdo.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(616, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbtnActionPerformed
        game game = new game();
        game.setVisible(true);
        dispose();
        //menu ya = new menu();
        
    }//GEN-LAST:event_playbtnActionPerformed

    private void highscoresbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoresbtnActionPerformed
        highscores high = new highscores();
        high.setVisible(true);
        dispose();
    }//GEN-LAST:event_highscoresbtnActionPerformed

    private void creditsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsbtnActionPerformed
       credits credits = new credits();
       credits.setVisible(true);
       dispose();
               
    }//GEN-LAST:event_creditsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        start ya = new start();
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ya.setVisible(true);
            }
        });
        
        ya.dancingman.setVisible(false);
        ya.playbtn.setVisible(false);
        ya.highscoresbtn.setVisible(false);
        ya.creditsbtn.setVisible(false);
        ya.lasagna.setVisible(false);
        
        //Screen n = new Screen();
            ya.lasagna.setVisible(true);
            ya.dancingman.setVisible(true);
            ya.playbtn.setVisible(true);
            ya.highscoresbtn.setVisible(true);
            ya.creditsbtn.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditsbtn;
    private javax.swing.JLabel dancingman;
    private javax.swing.JButton highscoresbtn;
    private javax.swing.JLabel lasagna;
    private javax.swing.JButton playbtn;
    private javax.swing.JPanel whatitdo;
    // End of variables declaration//GEN-END:variables
}
