/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tater
 */

package lasagna.hangman.start;

import java.util.logging.Level;
import java.util.logging.Logger;

public class BubbleGameEndScreen extends javax.swing.JFrame {

    /**
     * Creates new form BubbleGameEndScreen
     */
    public BubbleGameEndScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        YES = new javax.swing.JButton();
        NO = new javax.swing.JButton();
        initials = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("game");
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });

        question.setText("Congrats, you just got a new highscore, would you like to save it?");
        question.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                questionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton1.setText("to menu screen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        YES.setText("YES");
        YES.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                YESAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YESActionPerformed(evt);
            }
        });

        NO.setText("NO");
        NO.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                NOAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOActionPerformed(evt);
            }
        });

        initials.setText("Input initials in capital letters ");
        initials.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                initialsAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        initials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialsActionPerformed(evt);
            }
        });
        initials.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                initialsPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(initials, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YES)
                                        .addGap(90, 90, 90)
                                        .addComponent(NO)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(question, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(question)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YES)
                    .addComponent(NO))
                .addGap(18, 18, 18)
                .addComponent(initials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
    start x = new start();
    x.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void questionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_questionAncestorAdded
question.setVisible(false);    
if(GameScreen.finalScore>Hangman.highScore5){
    question.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_questionAncestorAdded

    private void initialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialsActionPerformed
initials.setVisible(false);    
if(GameScreen.finalScore>Hangman.highScore5){
    initials.setVisible(true);  
}// TODO add your handling code here:
    }//GEN-LAST:event_initialsActionPerformed

    private void YESAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_YESAncestorAdded
YES.setVisible(false);
if(GameScreen.finalScore>Hangman.highScore5){
    YES.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_YESAncestorAdded

    private void YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YESActionPerformed
if(GameScreen.finalScore>=Hangman.highScore1){ //1
           if(Hangman.highScore1>0){
               //moves 5 up
               Hangman.highScore5 = Hangman.highScore4;
               Hangman.highScore5init = Hangman.highScore4init;
               //moves 4 up
               Hangman.highScore4 = Hangman.highScore3;
               Hangman.highScore4init = Hangman.highScore3init;
               //moves 3 up
               Hangman.highScore3 = Hangman.highScore2;
               Hangman.highScore3init = Hangman.highScore2init;
                Hangman.highScore2 = Hangman.highScore1;
                //moves 2 up
               Hangman.highScore2init = Hangman.highScore1init;
               System.out.println(Hangman.highScore2init+Hangman.highScore2);
               
               //the new version will be above 
        
           }
           Hangman.highScore1 = GameScreen.finalScore;
           Hangman.highScore1init = initials.getText();
           System.out.println(Hangman.highScore1init);
       } else if(GameScreen.finalScore>=Hangman.highScore2&&GameScreen.finalScore<Hangman.highScore1){ //2
           if(Hangman.highScore2>0){
               Hangman.highScore5 = Hangman.highScore4;
               Hangman.highScore5init = Hangman.highScore4init;
               Hangman.highScore4 = Hangman.highScore3;
               Hangman.highScore4init = Hangman.highScore3init;
               Hangman.highScore3 = Hangman.highScore2;
               Hangman.highScore3init = Hangman.highScore2init;
               //new code above
               
           }
           Hangman.highScore2 = GameScreen.finalScore;
           Hangman.highScore2init = initials.getText();
           System.out.println(Hangman.highScore2init);
       } else if(GameScreen.finalScore>=Hangman.highScore3&&GameScreen.finalScore<Hangman.highScore2){//3
           if(Hangman.highScore3>0){
               
                Hangman.highScore5 = Hangman.highScore4;
               Hangman.highScore5init = Hangman.highScore4init;
               Hangman.highScore4 = Hangman.highScore3;
               Hangman.highScore4init = Hangman.highScore3init;
//new code 
//moves 3down
               
               //moves 4down
              
           }
           Hangman.highScore3 = GameScreen.finalScore;
           Hangman.highScore3init = initials.getText();
           System.out.println(Hangman.highScore3init);
       } else if(GameScreen.finalScore>=Hangman.highScore4&&GameScreen.finalScore<Hangman.highScore3){//4
           if(Hangman.highScore3>0){
               //moves 4down
               Hangman.highScore5 = Hangman.highScore4;
               Hangman.highScore5init = Hangman.highScore4init;
           }
           Hangman.highScore4 = GameScreen.finalScore;
           Hangman.highScore4init = initials.getText();
           System.out.println(Hangman.highScore4init);
       } else if(GameScreen.finalScore>=Hangman.highScore5&&GameScreen.finalScore<Hangman.highScore4){//5
           Hangman.highScore5 = GameScreen.finalScore;
           Hangman.highScore5init = initials.getText();
           System.out.println(Hangman.highScore5init);
       }
        try {
            Hangman.fileMethod(1);
        } catch (Exception ex) {
            Logger.getLogger(BubbleGameEndScreen.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_YESActionPerformed

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
jLabel1.setText("Your Final Score is "+GameScreen.finalScore);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOActionPerformed
NO.setVisible(false);
if(GameScreen.finalScore>Hangman.highScore5){
    NO.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_NOActionPerformed

    private void NOAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_NOAncestorAdded
NO.setVisible(false);
if(GameScreen.finalScore>GameScreen.highScore5){
    NO.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_NOAncestorAdded

    private void initialsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_initialsAncestorAdded

        
// TODO add your handling code here:
    }//GEN-LAST:event_initialsAncestorAdded

    private void initialsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_initialsPropertyChange
        initials.setVisible(false);
if(GameScreen.finalScore>GameScreen.highScore5){
    initials.setVisible(true);
} // TODO add your handling code here:
    }//GEN-LAST:event_initialsPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BubbleGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BubbleGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BubbleGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BubbleGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BubbleGameEndScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NO;
    private javax.swing.JButton YES;
    private javax.swing.JTextField initials;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
