package lasagna.hangman.start;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tater
 */
public class GameScreen extends javax.swing.JFrame {
public static int currentLowestScore;
public static int numberOfScores;
public static int highScore1;
public static int highScore2;
public static int highScore3;
public static int highScore4;
public static int highScore5;
public static double x=0;
public static double c=0;
public static String tcolor = "";
public static int currentScore;
public static int round;
public static int finalScore;
    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        purpleButton = new javax.swing.JButton();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        purpleButton.setText("newpurp");
        purpleButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                purpleButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        purpleButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                purpleButtonMouseMoved(evt);
            }
        });
        purpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleButtonActionPerformed(evt);
            }
        });

        redButton.setText("newred");
        redButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                redButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        redButton.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                redButtonMouseWheelMoved(evt);
            }
        });
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        blueButton.setText("newblue");
        blueButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                blueButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        blueButton.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                blueButtonMouseWheelMoved(evt);
            }
        });
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        greenButton.setText("newgreen");
        greenButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                greenButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        greenButton.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                greenButtonMouseWheelMoved(evt);
            }
        });
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        yellowButton.setText("newyellow");
        yellowButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                yellowButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        yellowButton.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                yellowButtonMouseWheelMoved(evt);
            }
        });
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(purpleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redButton)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(yellowButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(greenButton)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(purpleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(redButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(blueButton)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenButton)
                    .addComponent(yellowButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
 x = Math.random()*5+1;
 System.out.println(x);
 c= Math.random()*5+1;
 System.out.println(c);
 if((int)c==1){
     jLabel1.setForeground(Color.RED);
       tcolor="red";
 } else if((int)c==2){
     jLabel1.setForeground(Color.GREEN);
    tcolor="green";
 } else if((int)c==3){
      jLabel1.setForeground(Color.BLUE);
     tcolor="blue";
 } else if((int)c==4){
      jLabel1.setForeground(Color.YELLOW);
    tcolor="yellow";
 } else if((int)c==5){
     jLabel1.setForeground(Color.MAGENTA);
     tcolor="purple";
 }
 
if((int)x==1){
        jLabel1.setText("red");
       
} else if((int)x==2){
    jLabel1.setText("green");
    
} else if((int)x==3){
     jLabel1.setText("blue");
     
} else if((int)x==4) {
    jLabel1.setText("yellow");
   
} else if((int)x==5) {
     jLabel1.setText("purple");
     jLabel1.setForeground(Color.MAGENTA);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void purpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleButtonActionPerformed
    if(tcolor.equals("purple")){
            currentScore+=100;   
        }
        round++;
        if(round==5){
            //the correct final score for nick 
            finalScore = currentScore + game1.userScore;
            
            System.out.println("Final Score = " +finalScore);
            currentScore=0;
            round=0;
            dispose();
            //tell nick to change his end screen to GameScreen game = New GameScreen();
            //game.setVisible(true);
            BubbleGameEndScreen x = new BubbleGameEndScreen();
            x.setVisible(true);
        }
        System.out.println("current score = "+currentScore);
        System.out.println("round " + round );
        x = Math.random()*5+1;
        System.out.println(x);
        c= Math.random()*5+1;
 System.out.println(c);
 if((int)c==1){
     jLabel1.setForeground(Color.RED);
       tcolor="red";
 } else if((int)c==2){
     jLabel1.setForeground(Color.GREEN);
    tcolor="green";
 } else if((int)c==3){
      jLabel1.setForeground(Color.BLUE);
     tcolor="blue";
 } else if((int)c==4){
      jLabel1.setForeground(Color.YELLOW);
    tcolor="yellow";
 } else if((int)c==5){
     jLabel1.setForeground(Color.MAGENTA);
     tcolor="purple";
 }
        if((int)x==1){
            jLabel1.setText("red");
       
        } else if ((int)x==2){
            jLabel1.setText("green");
       
        } else if ((int)x==3){
            jLabel1.setText("blue");
       
        } else if ((int)x==4){
            jLabel1.setText("yellow");
       
        } else if ((int)x==5){
            jLabel1.setText("purple");
       
        }    // TODO add your handling code here:
    }//GEN-LAST:event_purpleButtonActionPerformed

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
if(tcolor.equals("red")){
            currentScore+=100;   
        }
        round++;
        if(round==5){
            //the correct final score for nick 
            finalScore = currentScore + game1.userScore;
            
            System.out.println("Final Score = " +finalScore);
            currentScore=0;
            round=0;
            dispose();
            //tell nick to change his end screen to GameScreen game = New GameScreen();
            //game.setVisible(true);
            BubbleGameEndScreen x = new BubbleGameEndScreen();
            x.setVisible(true);
        }
        System.out.println("current score = "+currentScore);
        System.out.println("round " + round );
        x = Math.random()*5+1;
        System.out.println(x);
        c= Math.random()*5+1;
 System.out.println(c);
 if((int)c==1){
     jLabel1.setForeground(Color.RED);
       tcolor="red";
 } else if((int)c==2){
     jLabel1.setForeground(Color.GREEN);
    tcolor="green";
 } else if((int)c==3){
      jLabel1.setForeground(Color.BLUE);
     tcolor="blue";
 } else if((int)c==4){
      jLabel1.setForeground(Color.YELLOW);
    tcolor="yellow";
 } else if((int)c==5){
     jLabel1.setForeground(Color.MAGENTA);
     tcolor="purple";
 }
        if((int)x==1){
            jLabel1.setText("red");
       
        } else if ((int)x==2){
            jLabel1.setText("green");
       
        } else if ((int)x==3){
            jLabel1.setText("blue");
       
        } else if ((int)x==4){
            jLabel1.setText("yellow");
       
        } else if ((int)x==5){
            jLabel1.setText("purple");
       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_redButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
if(tcolor.equals("yellow")){
            currentScore+=100;   
        }
        round++;
        if(round==5){
            //the correct final score for nick 
            finalScore = currentScore + game1.userScore;
            
            System.out.println("Final Score = " +finalScore);
            currentScore=0;
            round=0;
            dispose();
            //tell nick to change his end screen to GameScreen game = New GameScreen();
            //game.setVisible(true);
            BubbleGameEndScreen x = new BubbleGameEndScreen();
            x.setVisible(true);
        }
        System.out.println("current score = "+currentScore);
        System.out.println("round " + round );
        x = Math.random()*5+1;
        System.out.println(x);
        c= Math.random()*5+1;
 System.out.println(c);
 if((int)c==1){
     jLabel1.setForeground(Color.RED);
       tcolor="red";
 } else if((int)c==2){
     jLabel1.setForeground(Color.GREEN);
    tcolor="green";
 } else if((int)c==3){
      jLabel1.setForeground(Color.BLUE);
     tcolor="blue";
 } else if((int)c==4){
      jLabel1.setForeground(Color.YELLOW);
    tcolor="yellow";
 } else if((int)c==5){
     jLabel1.setForeground(Color.MAGENTA);
     tcolor="purple";
 }
        if((int)x==1){
            jLabel1.setText("red");
       
        } else if ((int)x==2){
            jLabel1.setText("green");
       
        } else if ((int)x==3){
            jLabel1.setText("blue");
       
        } else if ((int)x==4){
            jLabel1.setText("yellow");
       
        } else if ((int)x==5){
            jLabel1.setText("purple");
       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_yellowButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
if(tcolor.equals("green")){
            currentScore+=100;   
        }
        round++;
        if(round==5){
            //the correct final score for nick 
            finalScore = currentScore + game1.userScore;
            
            System.out.println("Final Score = " +finalScore);
            currentScore=0;
            round=0;
            dispose();
            //tell nick to change his end screen to GameScreen game = New GameScreen();
            //game.setVisible(true);
            BubbleGameEndScreen x = new BubbleGameEndScreen();
            x.setVisible(true);
        }
        System.out.println("current score = "+currentScore);
        System.out.println("round " + round );
        x = Math.random()*5+1;
        System.out.println(x);
        c= Math.random()*5+1;
 System.out.println(c);
 if((int)c==1){
     jLabel1.setForeground(Color.RED);
       tcolor="red";
 } else if((int)c==2){
     jLabel1.setForeground(Color.GREEN);
    tcolor="green";
 } else if((int)c==3){
      jLabel1.setForeground(Color.BLUE);
     tcolor="blue";
 } else if((int)c==4){
      jLabel1.setForeground(Color.YELLOW);
    tcolor="yellow";
 } else if((int)c==5){
     jLabel1.setForeground(Color.MAGENTA);
     tcolor="purple";
 }
        if((int)x==1){
            jLabel1.setText("red");
       
        } else if ((int)x==2){
            jLabel1.setText("green");
       
        } else if ((int)x==3){
            jLabel1.setText("blue");
       
        } else if ((int)x==4){
            jLabel1.setText("yellow");
       
        } else if ((int)x==5){
            jLabel1.setText("purple");
       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_greenButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
if(tcolor.equals("blue")){
            currentScore+=100;   
        }
        round++;
        if(round==5){
            //the correct final score for nick 
            finalScore = currentScore + game1.userScore;
            
            System.out.println("Final Score = " +finalScore);
            currentScore=0;
            round=0;
            dispose();
            //tell nick to change his end screen to GameScreen game = New GameScreen();
            //game.setVisible(true);
            BubbleGameEndScreen x = new BubbleGameEndScreen();
            x.setVisible(true);
        }
        System.out.println("current score = "+currentScore);
        System.out.println("round " + round );
        x = Math.random()*5+1;
        System.out.println(x);
        c= Math.random()*5+1;
 System.out.println(c);
 if((int)c==1){
     jLabel1.setForeground(Color.RED);
       tcolor="red";
 } else if((int)c==2){
     jLabel1.setForeground(Color.GREEN);
    tcolor="green";
 } else if((int)c==3){
      jLabel1.setForeground(Color.BLUE);
     tcolor="blue";
 } else if((int)c==4){
      jLabel1.setForeground(Color.YELLOW);
    tcolor="yellow";
 } else if((int)c==5){
     jLabel1.setForeground(Color.MAGENTA);
     tcolor="purple";
 }
        if((int)x==1){
            jLabel1.setText("red");
       
        } else if ((int)x==2){
            jLabel1.setText("green");
       
        } else if ((int)x==3){
            jLabel1.setText("blue");
       
        } else if ((int)x==4){
            jLabel1.setText("yellow");
       
        } else if ((int)x==5){
            jLabel1.setText("purple");
       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_blueButtonActionPerformed

    private void purpleButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_purpleButtonAncestorAdded
purpleButton.setBackground(Color.MAGENTA);        // TODO add your handling code here:
    }//GEN-LAST:event_purpleButtonAncestorAdded

    private void purpleButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleButtonMouseMoved
getRootPane().setDefaultButton(purpleButton);         // TODO add your handling code here:
    }//GEN-LAST:event_purpleButtonMouseMoved

    private void redButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_redButtonAncestorAdded
redButton.setBackground(Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_redButtonAncestorAdded

    private void blueButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_blueButtonAncestorAdded
blueButton.setBackground(Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_blueButtonAncestorAdded

    private void greenButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_greenButtonAncestorAdded
greenButton.setBackground(Color.GREEN);        // TODO add your handling code here:
    }//GEN-LAST:event_greenButtonAncestorAdded

    private void yellowButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_yellowButtonAncestorAdded
yellowButton.setBackground(Color.YELLOW);        // TODO add your handling code here:
    }//GEN-LAST:event_yellowButtonAncestorAdded

    private void redButtonMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_redButtonMouseWheelMoved
getRootPane().setDefaultButton(redButton);              // TODO add your handling code here:
    }//GEN-LAST:event_redButtonMouseWheelMoved

    private void blueButtonMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_blueButtonMouseWheelMoved
getRootPane().setDefaultButton(blueButton);              // TODO add your handling code here:
    }//GEN-LAST:event_blueButtonMouseWheelMoved

    private void yellowButtonMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_yellowButtonMouseWheelMoved
getRootPane().setDefaultButton(yellowButton);              // TODO add your handling code here:
    }//GEN-LAST:event_yellowButtonMouseWheelMoved

    private void greenButtonMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_greenButtonMouseWheelMoved
getRootPane().setDefaultButton(greenButton);              // TODO add your handling code here:
    }//GEN-LAST:event_greenButtonMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton purpleButton;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables
}
