/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lasagna.hangman.start;
//package lasagna.hangman.start.folder;

/**
 *
 * @author nic
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whatitdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BAR = new javax.swing.JProgressBar();
        progress = new javax.swing.JLabel();
        processes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        whatitdo.setBackground(new java.awt.Color(153, 153, 255));
        whatitdo.setForeground(new java.awt.Color(153, 153, 255));
        whatitdo.setToolTipText("");
        whatitdo.setPreferredSize(new java.awt.Dimension(600, 400));
        whatitdo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CS2450 HANGMAN V1.0");
        whatitdo.add(jLabel1);
        jLabel1.setBounds(100, 0, 395, 94);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TEAM L + ASAGNA");
        whatitdo.add(jLabel2);
        jLabel2.setBounds(100, 80, 370, 60);
        whatitdo.add(BAR);
        BAR.setBounds(40, 250, 540, 40);

        progress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progress.setText("0%");
        whatitdo.add(progress);
        progress.setBounds(300, 300, 30, 20);
        whatitdo.add(processes);
        processes.setBounds(40, 220, 230, 20);

        getContentPane().add(whatitdo, java.awt.BorderLayout.CENTER);
        whatitdo.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(616, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        menu ya = new menu();
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ya.setVisible(true);
            }
        });
        
        
        gametest game =  new gametest();
        game.setSize(600,400);
       
        if(game.begin==0){
        game.x=Math.random()*5+1;  
        game.begin++;
        game.x=(int)game.x;
        System.out.println(game.x);
        game.x=(int)game.x;

        if((int)game.x==1){
          game.target="abstract";
         
        } else if((int)game.x==2){
          game.target="cemetery";
        } else if((int)game.x==3){
           game.target="nurse";
        } else if ((int)game.x==4){
           game.target="pharmacy";
        } else if ((int)game.x==5){
            game.target="climbing";
        }
    System.out.println(game.target);
        }
        
        //game.setVisible(true);
        
        
        
        //Screen n = new Screen();
        try
        {
            for(int i = 0; i <= 100; i++)
            {
                //sc.BAR.setVisible(true);
                //sc.progress.setVisible(true);
                Thread.sleep(30);
                ya.BAR.setValue(i);
                ya.progress.setText(Integer.toString(i)+ "%");
                
                if(i == 10)
                    ya.processes.setText("Game Loading Please Wait");
                
                if(i == 25)
                    ya.processes.setText("Finding innocent bystander...");
                
                if(i == 60)
                    ya.processes.setText("They resisting  >:| ...");
                
                if(i == 85)
                    ya.processes.setText("Got em lol");
                
                
                    
            }
            
            
            //new Screen().setVisible(true); //makes screen disappear 
        } catch (Exception e)
        {
            //new Screen().setVisible(false);
            //n.setVisible(true);
            //sc.dispose();
        }
        //n.setVisible(true);
        //ya.dispose(); //gets rid of the splash screen      
            ya.jLabel1.setVisible(false);
            ya.jLabel2.setVisible(false);
            
            
            ya.BAR.setVisible(false);
            ya.progress.setVisible(false);
            ya.processes.setVisible(false);
            
           start start = new start();
           start.setVisible(true);
           ya.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BAR;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel processes;
    private javax.swing.JLabel progress;
    private javax.swing.JPanel whatitdo;
    // End of variables declaration//GEN-END:variables
}
