/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lasagna.hangman.start;
//package lasagna.hangman.start.folder;

/**
 *
 * @author nic
 */
public class highscores extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public highscores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whatitdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        highscore1 = new javax.swing.JLabel();
        highscore2 = new javax.swing.JLabel();
        highscore3 = new javax.swing.JLabel();
        highscore4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        whatitdo.setBackground(new java.awt.Color(153, 153, 255));
        whatitdo.setForeground(new java.awt.Color(153, 153, 255));
        whatitdo.setToolTipText("");
        whatitdo.setMaximumSize(new java.awt.Dimension(600, 400));
        whatitdo.setMinimumSize(new java.awt.Dimension(600, 400));
        whatitdo.setPreferredSize(new java.awt.Dimension(600, 400));
        whatitdo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HIGHSCORES");
        whatitdo.add(jLabel1);
        jLabel1.setBounds(100, 0, 395, 94);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ABC...00000");
        whatitdo.add(jLabel3);
        jLabel3.setBounds(200, 220, 200, 30);

        highscore1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        highscore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscore1.setText("ABC...00000");
        whatitdo.add(highscore1);
        highscore1.setBounds(200, 100, 200, 30);

        highscore2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        highscore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscore2.setText("ABC...00000");
        whatitdo.add(highscore2);
        highscore2.setBounds(200, 130, 200, 30);

        highscore3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        highscore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscore3.setText("ABC...00000");
        whatitdo.add(highscore3);
        highscore3.setBounds(200, 160, 200, 30);

        highscore4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        highscore4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscore4.setText("ABC...00000");
        whatitdo.add(highscore4);
        highscore4.setBounds(200, 190, 200, 30);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        whatitdo.add(jButton1);
        jButton1.setBounds(40, 340, 72, 30);

        getContentPane().add(whatitdo, java.awt.BorderLayout.CENTER);
        whatitdo.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(616, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        start start = new start();
        start.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        highscores ya = new highscores();
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ya.setVisible(true);
            }
        });
        
        
        
        
            
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highscore1;
    private javax.swing.JLabel highscore2;
    private javax.swing.JLabel highscore3;
    private javax.swing.JLabel highscore4;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel whatitdo;
    // End of variables declaration//GEN-END:variables
}
