/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lasagna.hangman.start;

/**
 *
 * @author nic
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        letterQ = new javax.swing.JButton();
        letterR = new javax.swing.JButton();
        letterW = new javax.swing.JButton();
        letterX = new javax.swing.JButton();
        letterV = new javax.swing.JButton();
        letterT = new javax.swing.JButton();
        letterU = new javax.swing.JButton();
        letterP = new javax.swing.JButton();
        letterY = new javax.swing.JButton();
        letterN = new javax.swing.JButton();
        letterZ = new javax.swing.JButton();
        letterO = new javax.swing.JButton();
        letterS = new javax.swing.JButton();
        letterD = new javax.swing.JButton();
        letterE = new javax.swing.JButton();
        letterJ = new javax.swing.JButton();
        letterK = new javax.swing.JButton();
        letterI = new javax.swing.JButton();
        letterG = new javax.swing.JButton();
        letterH = new javax.swing.JButton();
        letterC = new javax.swing.JButton();
        letterL = new javax.swing.JButton();
        letterA = new javax.swing.JButton();
        letterM = new javax.swing.JButton();
        letterB = new javax.swing.JButton();
        letterF = new javax.swing.JButton();
        Skipbutton = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        firstletter = new javax.swing.JLabel();
        thirdletter = new javax.swing.JLabel();
        fourthletter = new javax.swing.JLabel();
        secondletter = new javax.swing.JLabel();
        fifthletter = new javax.swing.JLabel();
        sixthletter = new javax.swing.JLabel();
        seventhletter = new javax.swing.JLabel();
        eighthletter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel8.setText("A");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letterQ.setText("Q");
        letterQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterQActionPerformed(evt);
            }
        });
        jPanel1.add(letterQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 477, -1, -1));

        letterR.setText("R");
        letterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterRActionPerformed(evt);
            }
        });
        jPanel1.add(letterR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 477, -1, -1));

        letterW.setText("W");
        letterW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterWActionPerformed(evt);
            }
        });
        jPanel1.add(letterW, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 477, -1, -1));

        letterX.setText("X");
        letterX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterXActionPerformed(evt);
            }
        });
        jPanel1.add(letterX, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 477, -1, -1));

        letterV.setText("V");
        letterV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterVActionPerformed(evt);
            }
        });
        jPanel1.add(letterV, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 477, -1, -1));

        letterT.setText("T");
        letterT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterTActionPerformed(evt);
            }
        });
        jPanel1.add(letterT, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 477, -1, -1));

        letterU.setText("U");
        letterU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterUActionPerformed(evt);
            }
        });
        jPanel1.add(letterU, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 477, -1, -1));

        letterP.setText("P");
        letterP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterPActionPerformed(evt);
            }
        });
        jPanel1.add(letterP, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 477, -1, -1));

        letterY.setText("Y");
        letterY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterYActionPerformed(evt);
            }
        });
        jPanel1.add(letterY, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 477, -1, -1));

        letterN.setText("N");
        letterN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterNActionPerformed(evt);
            }
        });
        jPanel1.add(letterN, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 477, -1, -1));

        letterZ.setText("Z");
        letterZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterZActionPerformed(evt);
            }
        });
        jPanel1.add(letterZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 477, -1, -1));

        letterO.setText("O");
        letterO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterOActionPerformed(evt);
            }
        });
        jPanel1.add(letterO, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 477, -1, -1));

        letterS.setText("S");
        letterS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterSActionPerformed(evt);
            }
        });
        jPanel1.add(letterS, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 477, -1, -1));

        letterD.setText("D");
        letterD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterDActionPerformed(evt);
            }
        });
        jPanel1.add(letterD, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 436, -1, -1));

        letterE.setText("E");
        letterE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterEActionPerformed(evt);
            }
        });
        jPanel1.add(letterE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 436, -1, -1));

        letterJ.setText("J");
        letterJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterJActionPerformed(evt);
            }
        });
        jPanel1.add(letterJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 436, -1, -1));

        letterK.setText("K");
        letterK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterKActionPerformed(evt);
            }
        });
        jPanel1.add(letterK, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 436, -1, -1));

        letterI.setText("I");
        letterI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterIActionPerformed(evt);
            }
        });
        jPanel1.add(letterI, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 436, -1, -1));

        letterG.setText("G");
        letterG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterGActionPerformed(evt);
            }
        });
        jPanel1.add(letterG, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 436, -1, -1));

        letterH.setText("H");
        letterH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterHActionPerformed(evt);
            }
        });
        jPanel1.add(letterH, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 436, -1, -1));

        letterC.setText("C");
        letterC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterCActionPerformed(evt);
            }
        });
        jPanel1.add(letterC, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 436, -1, -1));

        letterL.setText("L");
        letterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterLActionPerformed(evt);
            }
        });
        jPanel1.add(letterL, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 436, -1, -1));

        letterA.setText("A");
        letterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterAActionPerformed(evt);
            }
        });
        jPanel1.add(letterA, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 436, -1, -1));

        letterM.setText("M");
        letterM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterMActionPerformed(evt);
            }
        });
        jPanel1.add(letterM, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 436, -1, -1));

        letterB.setText("B");
        letterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBActionPerformed(evt);
            }
        });
        jPanel1.add(letterB, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 436, -1, -1));

        letterF.setText("F");
        letterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterFActionPerformed(evt);
            }
        });
        jPanel1.add(letterF, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 436, -1, -1));

        Skipbutton.setText("Skip");
        Skipbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Skipbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 60, 54, -1));

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setBorder(null);
        jTextField9.setFocusable(false);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 48, 10, 40));

        jTextField10.setBackground(new java.awt.Color(0, 0, 0));
        jTextField10.setBorder(null);
        jTextField10.setMinimumSize(new java.awt.Dimension(22, 22));
        jTextField10.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 318, 200, 10));

        jTextField11.setBackground(new java.awt.Color(0, 0, 0));
        jTextField11.setBorder(null);
        jTextField11.setMinimumSize(new java.awt.Dimension(22, 22));
        jTextField11.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 48, 200, 10));

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setBorder(null);
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 48, 10, 270));

        firstletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        firstletter.setText("A");
        jPanel1.add(firstletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 342, -1, -1));

        thirdletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        thirdletter.setText("A");
        jPanel1.add(thirdletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 342, -1, -1));

        fourthletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        fourthletter.setText("A");
        jPanel1.add(fourthletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 342, -1, -1));

        secondletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        secondletter.setText("A");
        jPanel1.add(secondletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 342, -1, -1));

        fifthletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        fifthletter.setText("A");
        jPanel1.add(fifthletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 342, -1, -1));

        sixthletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        sixthletter.setText("A");
        jPanel1.add(sixthletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 342, -1, -1));

        seventhletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        seventhletter.setText("A");
        jPanel1.add(seventhletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 342, -1, -1));

        eighthletter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        eighthletter.setText("A");
        jPanel1.add(eighthletter, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 342, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\face1.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, -10, 82, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\body1.png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 50, 21, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\rightarm1.png")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 50, 90, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\leftarm1.png")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 70, 50, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\leftleg1.png")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 110, 50, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\rightleg1.png")); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 110, 50, 50);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 120, 260));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(null);

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setBorder(null);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(260, 50, 64, 10);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setBorder(null);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(190, 50, 64, 10);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setBorder(null);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(400, 50, 64, 10);

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setBorder(null);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(330, 50, 64, 10);

        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setBorder(null);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(470, 50, 64, 10);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(120, 50, 64, 10);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setBorder(null);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(50, 50, 64, 10);

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setBorder(null);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(540, 50, 64, 10);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 660, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(746, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void letterCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterCActionPerformed
        
    }//GEN-LAST:event_letterCActionPerformed

    private void letterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterAActionPerformed

    private void letterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterBActionPerformed

    private void letterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterFActionPerformed

    private void letterDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterDActionPerformed

    private void letterEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterEActionPerformed

    private void letterJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterJActionPerformed

    private void letterKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterKActionPerformed

    private void letterIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterIActionPerformed

    private void letterGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterGActionPerformed

    private void letterHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterHActionPerformed

    private void letterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterLActionPerformed

    private void letterMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterMActionPerformed

    private void letterQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterQActionPerformed

    private void letterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterRActionPerformed

    private void letterWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterWActionPerformed

    private void letterXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterXActionPerformed

    private void letterVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterVActionPerformed

    private void letterTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterTActionPerformed

    private void letterUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterUActionPerformed

    private void letterPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterPActionPerformed

    private void letterYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterYActionPerformed

    private void letterNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterNActionPerformed

    private void letterZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterZActionPerformed

    private void letterOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterOActionPerformed

    private void letterSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterSActionPerformed

    private void SkipbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkipbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Skipbutton;
    private javax.swing.JLabel eighthletter;
    private javax.swing.JLabel fifthletter;
    private javax.swing.JLabel firstletter;
    private javax.swing.JLabel fourthletter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton letterA;
    private javax.swing.JButton letterB;
    private javax.swing.JButton letterC;
    private javax.swing.JButton letterD;
    private javax.swing.JButton letterE;
    private javax.swing.JButton letterF;
    private javax.swing.JButton letterG;
    private javax.swing.JButton letterH;
    private javax.swing.JButton letterI;
    private javax.swing.JButton letterJ;
    private javax.swing.JButton letterK;
    private javax.swing.JButton letterL;
    private javax.swing.JButton letterM;
    private javax.swing.JButton letterN;
    private javax.swing.JButton letterO;
    private javax.swing.JButton letterP;
    private javax.swing.JButton letterQ;
    private javax.swing.JButton letterR;
    private javax.swing.JButton letterS;
    private javax.swing.JButton letterT;
    private javax.swing.JButton letterU;
    private javax.swing.JButton letterV;
    private javax.swing.JButton letterW;
    private javax.swing.JButton letterX;
    private javax.swing.JButton letterY;
    private javax.swing.JButton letterZ;
    private javax.swing.JLabel secondletter;
    private javax.swing.JLabel seventhletter;
    private javax.swing.JLabel sixthletter;
    private javax.swing.JLabel thirdletter;
    // End of variables declaration//GEN-END:variables
}
