/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lasagna.hangman.start;
//package lasagna.hangman.start.folder;

/**
 *
 * @author nic
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whatitdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BAR = new javax.swing.JProgressBar();
        progress = new javax.swing.JLabel();
        processes = new javax.swing.JLabel();
        playbtn = new javax.swing.JButton();
        highscoresbtn = new javax.swing.JButton();
        creditsbtn = new javax.swing.JButton();
        dancingman = new javax.swing.JLabel();
        lasagna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        whatitdo.setBackground(new java.awt.Color(153, 153, 255));
        whatitdo.setForeground(new java.awt.Color(153, 153, 255));
        whatitdo.setToolTipText("");
        whatitdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CS2450 HANGMAN V1.0");
        whatitdo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 395, 94));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(lasagna);
        jLabel2.setText("TEAM L + ASAGNA");
        whatitdo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 370, 60));
        whatitdo.add(BAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 540, 40));

        progress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progress.setText("0%");
        whatitdo.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));
        whatitdo.add(processes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 230, 20));

        playbtn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        playbtn.setText("PLAY");
        playbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbtnActionPerformed(evt);
            }
        });
        whatitdo.add(playbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 160, 40));

        highscoresbtn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        highscoresbtn.setText("HIGHSCORES");
        whatitdo.add(highscoresbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 160, 40));

        creditsbtn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        creditsbtn.setText("CREDITS");
        whatitdo.add(creditsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 160, 40));

        dancingman.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\5a65dcc4e4a067fc85e1c85a3d8809d0.gif")); // NOI18N
        dancingman.setLabelFor(dancingman);
        whatitdo.add(dancingman, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 430, 330));

        lasagna.setIcon(new javax.swing.ImageIcon("C:\\Users\\nic\\Documents\\NetBeansProjects\\hangman\\58f5578a4be18ec292b7a4374bebbe3f-lasagna-dish-illustration.png")); // NOI18N
        whatitdo.add(lasagna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(whatitdo, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(whatitdo, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        whatitdo.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(774, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbtnActionPerformed
        game game = new game();
        game.setVisible(true);
        dispose();
        //menu ya = new menu();
        
    }//GEN-LAST:event_playbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        menu ya = new menu();
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ya.setVisible(true);
            }
        });
        
        ya.dancingman.setVisible(false);
        ya.playbtn.setVisible(false);
        ya.highscoresbtn.setVisible(false);
        ya.creditsbtn.setVisible(false);
        ya.lasagna.setVisible(false);
        
        //Screen n = new Screen();
        try
        {
            for(int i = 0; i <= 100; i++)
            {
                //sc.BAR.setVisible(true);
                //sc.progress.setVisible(true);
                Thread.sleep(30);
                ya.BAR.setValue(i);
                ya.progress.setText(Integer.toString(i)+ "%");
                
                if(i == 10)
                    ya.processes.setText("Game Loading Please Wait");
                
                if(i == 25)
                    ya.processes.setText("Finding innocent bystander...");
                
                if(i == 60)
                    ya.processes.setText("They resisting  >:| ...");
                
                if(i == 85)
                    ya.processes.setText("Got em lol");
                
                
                    
            }
            
            
            //new Screen().setVisible(true); //makes screen disappear 
        } catch (Exception e)
        {
            //new Screen().setVisible(false);
            //n.setVisible(true);
            //sc.dispose();
        }
        //n.setVisible(true);
        //ya.dispose(); //gets rid of the splash screen      
            ya.jLabel1.setVisible(false);
            ya.jLabel2.setVisible(false);
            
            ya.BAR.setVisible(false);
            ya.progress.setVisible(false);
            ya.processes.setVisible(false);
            
            ya.lasagna.setVisible(true);
            ya.dancingman.setVisible(true);
            ya.playbtn.setVisible(true);
            ya.highscoresbtn.setVisible(true);
            ya.creditsbtn.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BAR;
    private javax.swing.JButton creditsbtn;
    private javax.swing.JLabel dancingman;
    private javax.swing.JButton highscoresbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lasagna;
    private javax.swing.JButton playbtn;
    private javax.swing.JLabel processes;
    private javax.swing.JLabel progress;
    private javax.swing.JPanel whatitdo;
    // End of variables declaration//GEN-END:variables
}
